import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global/globals.css";
import "./loader.css"
import { ThemeProvider } from "@mui/material";
import { lightTheme } from "./styles/MUI/theme";
import LayoutWrapper from "@/components/common/LayoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pi Techniques Pvt. Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="bg-black" >
     <meta charSet="UTF-8" />
    <meta name="description" content="pi tech" />
    <meta name="keywords" content="pi tech" />
    <meta name="author" content="pi tech" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <body className={inter.className} style={{backgroundColor: '#f6f6f6'}}>
      <ThemeProvider theme={lightTheme}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </ThemeProvider>
    </body>
    </html>
  );
}
