// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global/globals.css";
import { NavbarComponent } from "@/components/header/Navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@mui/material";
import { lightTheme } from "./styles/MUI/theme";
// import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pi Techniques Pvt. Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const noHeaderPaths = ['/admin', '/register'];
  // const shouldShowHeader = !noHeaderPaths.includes(pathname);
  return (
    <html lang="en" className="bg-black" >
    <body className={inter.className} style={{backgroundColor: '#f6f6f6'}}>
      <ThemeProvider theme={lightTheme}>
        <NavbarComponent />
        {children}
        {/* <NewsLetterComponent/> */}
        <Footer/>
        </ThemeProvider>
        </body>
    </html>
  );
}
