import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global/globals.css";
import "@/styles/loader.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import LayoutWrapper from "@/components/common/layoutWrapper";
import { ReactNode } from "react";
import { lightTheme } from "@/styles/MUI/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="pi tech" />
        <meta name="keywords" content="pi tech" />
        <meta name="author" content="pi tech" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className} style={{ backgroundColor: "#f4f4f4" }}>
        <ThemeProvider theme={lightTheme}>
          <CssBaseline />
          <LayoutWrapper>{children}</LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
