// data/jobs.ts
export interface Job {
  slug: string;
  title: string;
  experience: string;
  jobcode: string;
  responsibilities?: string[] | Record<string, string[]>;
  qualifications?: string[];
  skills?: string[];
  basicskills?: string[];
}

export const jobs: Job[] = [
  {
    slug: "Azure_Data_Engineer",
    title: "Azure Data Engineer",
    experience: "2 - 5 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Data Modelling: Design and implement data models, including measures and dimensions, to support business intelligence and analytical reporting requirements.",
      "Azure Data Factory Development: Create, manage, and optimize data pipelines in Azure Data Factory to extract, transform, and load (ETL) data from various sources into the data warehouse.",
      "Dimensional Modelling: Develop and implement dimensional models for data warehousing, ensuring efficient storage and retrieval of data for analytical purposes.",
      "ETL Processes: Build and maintain ETL processes within Azure Data Factory to transform and cleanse data before loading it into the data warehouse.",
      "Integration with Analytics Services: Collaborate with data scientists and analysts to integrate Azure Data Factory with analytics services such as Azure Synapse Analytics, Azure Databricks, and Power BI.",
      "Data Quality and Governance: Implement data quality checks and governance measures to ensure the accuracy, completeness, and consistency of data stored in the data warehouse.",
      "Performance Tuning: Monitor and optimize data warehouse performance, including query performance and data loading processes, to meet performance and scalability requirements.",
      "Security and Compliance: Implement security measures for data access and ensure compliance with data governance policies and regulatory requirements.",
      "Documentation: Create and maintain documentation for data models, ETL processes, and data warehouse configurations.",
      "Collaboration: Work closely with business analysts, data scientists, and other stakeholders to understand reporting requirements and deliver effective data solutions.",
    ],
    qualifications: [
      "2 - 5 years of experience",
      "Bachelor’s degree in computer science, Information Technology, or a related field.",
      "Strong experience with Azure Data Factory, Azure Synapse Analytics, and other Azure data services.",
      "Proficiency in SQL and data querying languages.",
      "Expertise in dimensional modeling and data warehousing concepts.",
      " Hands-on experience with ETL processes and tools.",
      "Familiarity with analytics and reporting tools, such as Power BI.",
      "Knowledge of cloud computing concepts and services, especially within the Microsoft Azure ecosystem.",
      "Strong problem-solving and troubleshooting skills.",
      "Certifications such as Microsoft Certified: Azure Data Engineer Associate are a plus.",
    ],
    skills: [
      "MongoDB certification (e.g., MongoDB Certified Database Administrator)",
      "Experience with MongoDB databases. (Minimum of 3 years experience as DBA)",
      "Experience with other NoSQL DB (e.g. CosmoDB, DynamoDB, Cassandra etc)",
      "Familiarity with containerization technologies (e.g., Docker, Kubernetes).",
    ],
  },
  {
    slug: "Mongo_DBA",
    title: "Mongo DBA",
    experience: "3 - 6 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Install, configure, and maintain MongoDB database servers and clusters.",
      "Perform routine database maintenance tasks, including backups, restores, and disaster recovery procedures.",
      "Monitor database performance, identify and resolve performance bottlenecks, and optimize query performance.",
      "Design and implement database security measures, including access control, authentication, and encryption.",
      "Ensure high availability and fault tolerance of MongoDB deployments through replication and clustering.",
      "Plan and execute database upgrades and migrations while minimizing downtime.",
      "Collaborate with development teams to design efficient database schemas and troubleshoot application-related database issues.",
      "Develop and maintain documentation of database configurations, processes, and procedures.",
      "Participate in on-call support and respond to database-related incidents and emergencies.",
      "Stay up-to-date with MongoDB best practices, updates, and emerging trends in NoSQL databases.",
    ],
    qualifications: [
      "3 - 6 years of experience",
      "MongoDB certification (e.g., MongoDB Certified Database Administrator).",
      " Experience with MongoDB databases. (Minimum of 3 years experience as DBA)",
      "Experience with other NoSQL DB (e.g. CosmoDB, DynamoDB, Cassandra etc)",
      " Familiarity with containerization technologies (e.g., Docker, Kubernetes).",
    ],
    skills: [
      "MongoDB Shell (mongo), Atlas, Compass, MongoDB Ops Manager, Studio 3T (Optional)",
    ],
  },
  {
    slug: "SCRUM_MASTER",
    title: "Scrum Master",
    experience: "4 - 8 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "The Scrum Master will be responsible for facilitating and ensuring the effective implementation of the Scrum framework within our Agile teams. This role involves guiding, coaching, and mentoring the team to follow Scrum practices, remove impediments, and improve productivity. The Scrum Master will work closely with Product Owners, Development Teams, and other stakeholders to ensure successful project delivery.",
      "Facilitate Scrum Events: Plan and conduct daily stand-ups, sprint planning, sprint reviews, and retrospectives to ensure efficient team collaboration and project progress. Record minutes of meetings and track action items.",
      "Coach and Mentor: Guide the team and organization on how to use Agile/Scrum practices and values to delight customers. Mentor team members in Agile methodologies and practices.",
      "Remove Impediments: Identify and remove any obstacles that hinder the team’s progress and productivity. Ensure the team can focus on their work without unnecessary interruptions.",
      "Support Product Owner: Assist the Product Owner with backlog management, refinement, and prioritization. Ensure the team understands the product backlog and sprint goals.",
      "Foster Collaboration: Promote a collaborative team environment where open communication and feedback are encouraged. Facilitate team discussions and decision-making processes.",
      "Track and Report Progress: Monitor team performance using Agile metrics (e.g., burn-down charts, velocity) and provide regular updates to stakeholders on the progress and health of the team.",
      "Continuous Improvement: Encourage and facilitate continuous improvement within the team. Implement process improvements based on retrospective feedback and best practices.",
      "Promote Agile Culture: Advocate for Agile principles and values within the organization. Help create an environment that embraces change, innovation, and continuous improvement.",
    ],
    qualifications: ["4 - 8 years of experience"],
    skills: [],
  },
  {
    slug: "Software_Tester",
    title: "Software Tester",
    experience: "0 - 4 YRS OF EXPERIENCE",
    jobcode: "PI023",
    qualifications: [
      "0 - 4 years of experience",
      "Experience in manual testing",
      "Experience in working in agile methodology",
      "Knowledge of testing life cycle and testing process",
      "Should have knowledge of QA processes like test plans, test cases, and bug reporting",
      "Good knowledge of Database Testing, Regression Testing, Integration Testing, Functional Testing, Smoke Testing, Security Testing, Sanity Testing, Performance Testing, Mobile Testing, etc.",
      "Should have knowledge of bug tracking tools like JIRA, Team Foundation Server",
      "Team player as well as a self-starter who needs little supervision",
    ],
  },
  {
    slug: "Senior_Tester",
    title: "Senior Tester",
    experience: "4+ YRS OF EXPERIENCE",
    jobcode: "PI023",
    qualifications: ["4+ years of experience"],
    skills: [
      "Strong experience in manual testing",
      "Experience in working in agile methodology. Involved in all meetings – sprint planning, daily scrum calls, etc.",
      "Demo of user stories to client/stakeholder",
      "Updating test plan status to the test manager on a weekly basis",
      "Should have knowledge of QA processes like test plans, test cases, and bug reporting",
      "Knowledge of testing life cycle and testing process",
      "Good knowledge of Database Testing, Regression Testing, Integration Testing, Functional Testing, Smoke Testing, Security Testing, Sanity Testing, Performance Testing, Mobile Testing, etc.",
      "Should have knowledge of bug tracking tools like JIRA, Team Foundation Server",
      "Good to have knowledge of automation testing tools and technologies",
      "Ability to work under pressure, and deliver on time",
      "Team player as well as a self-starter who needs little supervision",
    ],
    responsibilities: [
      "Excellent written and verbal communication skills",
      "Outstanding teamwork and collaboration skills",
      "Understanding of software development life-cycle and methodologies",
      "Ability to troubleshoot, research, and work through complex problems",
      "Good presentation skills",
    ],
  },
  {
    slug: "DevOps_Engineer",
    title: "DevOps Engineer",
    experience: "2 - 5 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Build Automation: Develop and maintain automated build scripts and processes to compile, package, and version software applications efficiently.",
      "Continuous Integration/Continuous Deployment (CI/CD): Design, implement, and improve CI/CD pipelines to automate the build, test, and deployment phases, ensuring rapid and reliable software delivery.",
      "Version Control: Manage and optimize version control systems (e.g., Git) to ensure code repositories are well-structured, maintainable, and tagged appropriately for builds.",
      "Artifact Management: Implement and manage artifact repositories (e.g., Harbor) to store and distribute build artifacts, libraries, and dependencies.",
      "Build Environment Configuration: Create and maintain consistent and reproducible build environments, including configuring build servers, tools, and dependencies.",
      "Quality Assurance Integration: Collaborate with QA teams to integrate automated testing into the build and deployment pipelines, ensuring code quality and reliability.",
      "Deployment Automation: Automate the deployment of applications to various environments, including development, staging, and production, using tools like container orchestration platforms (e.g., Kubernetes) or MSI / PowerShell.",
      "Monitoring and Reporting: Implement monitoring and reporting tools to track build and deployment performance, identify bottlenecks, and resolve issues proactively.",
      "Documentation: Maintain detailed documentation of build and release processes, procedures, and version history.",
      "Scripting and Automation: Develop scripts and automation workflows to improve efficiency, reduce manual intervention, and enhance traceability in the build and release processes.",
      "Change Management: Implement and enforce change control processes to track and manage code changes, configurations, and dependencies.",
      "Collaboration: Collaborate with development teams to understand application requirements and provide support in resolving build-related issues.",
    ],
    qualifications: [
      "2 - 5 years of experience",
      "Proven experience in build engineering, release engineering, or related roles within a DevOps or Agile environment.",
      "Strong understanding of CI/CD concepts, version control systems, and automation tools.",
      "Familiarity with scripting languages (e.g. PowerShell, batch, shell) and build automation tools (e.g., AzureDevOps, Jenkins, GitLab CI/CD, Travis CI).",
      "Experience with containerization and container orchestration tools (e.g., Docker, Kubernetes) is a must.",
      "Knowledge of DevOps best practices and principles.",
      "Relevant certifications in DevOps, CI/CD, or related areas are advantageous.",
    ],
    skills: [
      "Excellent teamwork and collaboration skills to work effectively with cross-functional teams.",
      "Analytical mindset for troubleshooting, root cause analysis, and performance optimization.",
      "Adaptability and a commitment to continuous learning and staying updated with industry trends.",
      "Attention to detail and a dedication to maintaining high standards of code quality and reliability.",
      "Strong communication skills for facilitating collaboration, sharing information, and presenting ideas.",
    ],
  },
  {
    slug: "MERN_DEVELOPER",
    title: "MERN Developer",
    experience: "3 - 6 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: {
      "Front-end Development": [
        "Develop user-friendly web interfaces using React.js.",
        "Implement responsive design principles for a seamless user experience across various devices and screen sizes.",
        "Integrate third-party APIs and libraries as needed.",
        "Debug and optimize client-side code for performance and scalability.",
      ],
      "Back-end Development": [
        "Build and maintain server-side applications using Node.js and Express.js.",
        "Design and implement RESTful APIs for data communication.",
        "Create and manage databases using MongoDB, including schema design, indexing, and querying.",
        "Implement user authentication and authorization mechanisms.",
      ],
      "Full-stack Development": [
        "Collaborate with front-end and back-end developers to ensure seamless integration between the client and server sides.",
        "Work on both new projects and the enhancement of existing applications.",
      ],
      Documentation: [
        "Create and maintain technical documentation for code, APIs, and system architecture.",
        "Collaborate with other team members to ensure knowledge sharing.",
      ],
      "Stay Current with Industry Trends": [
        "Keep up-to-date with the latest trends and technologies in web development.",
        "Proactively suggest improvements and optimizations for existing projects.",
      ],
    },
    skills: [
      "Bachelor's degree in Computer Science, Information Technology, or related field (or equivalent work experience).",
      "Proven experience as a MERN developer or similar role.",
      "Strong proficiency in JavaScript, HTML, CSS, and related technologies.",
      "Proficiency in React.js for front-end development.",
      "Proficiency in Node.js and Express.js for back-end development.",
      "Experience with MongoDB or other NoSQL databases.",
      "Knowledge of RESTful API design and development.",
      "Familiarity with version control systems (e.g., Git).",
      "Experience with deployment and hosting platforms.",
      "Strong problem-solving and debugging skills.",
      "Excellent teamwork and communication skills.",
      "Ability to work independently and meet project deadlines.",
    ],
    qualifications: [
      "3 - 6 years of experience",
      "Experience with other front-end libraries and frameworks (e.g., Redux, Angular, Vue.js).",
      "Knowledge of GraphQL.",
      "Familiarity with containerization and orchestration (e.g., Docker, Kubernetes).",
      "Experience with continuous integration and continuous deployment (CI/CD) pipelines.",
      "Understanding of web security best practices.",
    ],
  },
  {
    slug: "Business_Analyst",
    title: "Business Analyst",
    experience: "5 - 7 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Ability to understand business requirements and translate them into detailed use cases and break them down into user stories/tasks.",
      "Acting as an interface between the client, technical teams and support teams.",
      "Effectively communicating with internal teams and client to deliver functional requirements.",
      "Create functional specifications for developers and testers.",
      "Plans sprints, monitor daily scrum meetings to identify and resolves impediments.",
      "Closely working with UX team for new UI designs and reviews.",
      "Identifying, managing and controlling changes provided by client. Tracking and reporting progress to all responsible stakeholders.",
      "Test and audit the functionality to assess the quality of deliverables at periodic intervals. Responsible for providing UAT support.",
      "Ability to create BRDs, User Stories, Flow diagrams and UX design.",
      "Monitor the testing tasks and practices on a regular basis to ensure the product testing is on track.",
      "Conducting product demos to client on a regular basis.",
      "Investigate and respond to routine or standard requests and queries from the client.",
      "Providing post release go-live support for resolving issues.",
    ],
    qualifications: [
      "5+ years experience as IT Business Analyst",
      "Well-versed with SDLC concepts and ability to work cohesively with Dev and QA team-members.",
      "Project management / Agile / Scrum experience. Experience in using Jira to manage projects.",
      "Experience in Web and Windows application.",
      "Good to have - Previous experience or background on Shipping ERP systems and technology.",
      "Database query skills (e.g. Microsoft SQL or equivalent).",
      "Strong verbal and written communication skills.",
    ],
  },
  {
    slug: "Web_Developer ",
    title: "Web Developer",
    experience: "1 - 3 YRS OF EXPERIENCE",
    jobcode: "PI023",
    qualifications: [
      "1 - 3 years of experience",
      "WordPress, Joomla, Opencart, Shopify etc.",
      "Experience and good knowledge in responsive design frameworks like Bootstrap.",
      "Ability to handle tasks independently.",
      "Converting PSD into HTML, CSS, JavaScript & jQuery Validate.",
      "Maintaining Websites of Clients.",
      "Creating HTML based Newsletters and emailers.",
      "Optimize application for maximum speed and scalability.",
      "Basic understanding of server-side CSS pre-processing platforms, such as LESS and SASS.",
      "Proficient understanding of cross-browser compatibility issues and ways to work around them.",
      "Must have completed at least 3 live projects in HTML5 & CSS3 with responsive/fluid layout approach.",
      "Should be capable of creating a basic webpage from scratch.",
      "Coordinate with Design and Product team to deliver best-in quality Website/Applications.",
    ],
    skills: [
      "HTML5",
      "CSS3",
      "jQuery",
      "JavaScript",
      "Bootstrap",
      "Responsive Design",
      "WordPress Developer",
      "UI Developer",
      "UX Developer",
      "WordPress Customization",
    ],
  },
  {
    slug: "JS_REPORT_DEVELOPER",
    title: "JS Report Developer ",
    experience: "1 - 3 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Need a skilled jsreport Developer to design, develop, and maintain custom reports using jsreport. The ideal candidate will have a background in web development, data management, and experience with jsreport. This role involves working closely with our development team and clients to deliver robust and scalable reporting solutions.",
      "Design and develop custom reports using jsreport.",
      "Create and manage templates using Handlebars (or other templating engines supported by jsreport).",
      "Bind JSON data to templates to generate dynamic content.",
      "Style reports using HTML and CSS, ensuring they are responsive and visually appealing.",
      "Configure jsreport to meet specific client requirements, including setting up templates, scripts, and assets.",
      "Integrate jsreport with back-end systems and APIs to fetch and manage data.",
      "Debug and troubleshoot issues in report generation and rendering.",
      "Collaborate with cross-functional teams to understand reporting needs and deliver solutions.",
      "Maintain and update existing reports, ensuring data accuracy and consistency.",
      "Deploy jsreport solutions on servers and manage ongoing maintenance.",
    ],
    qualifications: [
      "1 - 3 years of experience",
      "Proven experience in web development using JavaScript, HTML, and CSS.",
      "Proficiency in Handlebars or similar templating engines.",
      "Strong understanding of JSON data structures and data binding techniques.",
      "Experience with jsreport Studio and configuring jsreport templates and extensions.",
      "Knowledge of RESTful APIs and how to consume them for data integration.",
      "Ability to use browser developer tools for debugging and testing.",
      "Experience with version control systems like Git.",
      "Strong problem-solving skills and attention to detail.",
      "Communication and collaboration skills.",
    ],
  },
  {
    slug: "Application_Packaging",
    title: "Application Packaging",
    experience: "2 - 4 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Create application packages for the deployment of software applications to client environments.",
      "Work according to the company's application packaging life-cycle.",
      "Responsible for creating application update workflows (e.g., creating processes for updating application packages every time a new release is published).",
      "Quality testing of application packages on various Windows environments.",
      "Documentation of packages, error codes, and resolutions of application packages.",
      "Manage application and software update testing on virtual workstations.",
      "Work with customers to resolve issues within the agreed SLAs.",
      "Liaise with customers, stakeholders, and application owners to establish and maintain working relationships.",
      "Provide specialist technical support for delivery teams.",
      "Troubleshoot and resolve application and software update deployment and installation incident requests.",
      "Work without supervision and report to the technical manager on a daily basis.",
    ],
    qualifications: [
      "2 - 4 years of experience",
      "Good to have experience in creating application packages using Advanced Installer.",
      "Able to write custom action scripts for MSI packaging.",
      "Experience in PowerShell automation and VBScript automation.",
      "Excellent technical knowledge of packaging protocols, operating systems, and standards.",
      "Experience with facilitating complex and enterprise-scale software deployments.",
      "Extensive experience working with Windows desktop/web systems in a large, diverse, and distributed environment.",
      "Technical knowledge about hosting websites on IIS and hosting Windows services.",
      "Good to have knowledge of C# language.",
    ],
  },
  {
    slug: "Build_Release_Engineer",
    title: "Build Release Engineer",
    experience: "3 - 4 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Oversee all builds and deployment of releases to production and non-production environments.",
      "Integrate submitted/changed code into a release branch in our source control system.",
      "Ensure that the automated build and test suites run smoothly.",
      "Act as a Gatekeeper to all environments including production, ensuring proper release procedures are followed.",
      "Actively participate in the establishment, improvement, documentation, communication, and enforcement of configuration and change management processes for software systems.",
      "Define and oversee software, hardware, and system migrations between environments including releases to production.",
      "Generate release notes to accompany each major release.",
      "Maintain configuration status of development, test, and production environments.",
      "Recommend process improvements and train junior resources on Build & Release and Change Management.",
      "Automate build & deployment processes for all legacy, web-based, and database applications.",
      "Create SQL comparison reports and distribute them to the team.",
      "Monitor performance of the application based on predefined criteria.",
    ],
    qualifications: ["3 to 4 Years Experience "],
    skills: [
      "Azure DevOps",
      "Microsoft TFS",
      "GIT",
      "Microsoft Server",
      "IIS",
      "PowerShell scripting",
      "Windows services",
    ],
  },
  {
    slug: "WCF_Developer_(.NET)",
    title: "WCF Developer (.NET)",
    experience: "3+ YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Build and maintain high performance, scalable software systems.",
      "Improve the reliability and efficiency of our products’ core modules.",
      "Develop elegant solutions to complex problems.",
      "Implement new features, changes, enhancements, etc. to the project.",
      "Perform QA testing if necessary and address, escalate software quality issues as they arise.",
      "Work with team to make sure that software runs optimally in production.",
      "Contribute ideas for new features and identify areas for improvement proactively.",
      "Collaborate with product team to define clear requirements, deliverables, and milestones for new projects.",
      "Design, test, develop, and deploy production-ready applications.",
    ],
    qualifications: [
      "3+ years of development experience in Microsoft .NET specifically C# and SQL Server.",
      "Minimum 2 years of work experience in web service / WCF development.",
      "Minimum 2 years of development experience with Entity Framework (or any other ORM).",
      "Very strong C# fundamentals and experience in building applications in C#.",
      "Experience with SQL Server, and solid knowledge of SQL programming and T-SQL queries.",
      "Strong knowledge of object-oriented design, data structures, design patterns, algorithms, and programming skills.",
      "Good communication skills up line, as well as peer-to-peer.",
      "Excellent project and time management skills.",
      "Must be able to work well independently or in a team environment.",
      "Agile mindset and ability to thrive in a fast-paced working environment.",
    ],
  },
  {
    slug: "SQL_Database_Developer",
    title: "SQL Database Developer",
    experience: "3 to 5 YRS OF EXPERIENCE",
    jobcode: "PI023",
    qualifications: [
      "At least 3+ years of SQL Server development experience in a fast-paced, collaborative IT work environment.",
      "Fluent SQL scripting languages.",
      "Demonstrated experience writing complex stored procedures.",
      "Proven experience troubleshooting and solving complex databases schemas/warehouses.",
      "Experience with performance tuning stored procedures and SQL.",
      "Experience in MS SQL.",
      "Experience in database design and gathering database requirements.",
      "Demonstrated ability to work under minimal supervision on complex projects.",
      "Demonstrated ability and willingness to learn and quickly comprehend new concepts.",
      "Demonstrated strong judgment and decision-making ability.",
      "Strong consultative, analytical and problem-solving skills.",
      "Cross-functional collaboration skills.",
      "Experience / familiarity with at least one programming language such as Java / C#, though not as a main-stream programmer.",
    ],
  },
  {
    slug: "Mobile_Developer",
    title: "Mobile Developer",
    experience: "2 to 4 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Support the entire application lifecycle (concept, design, support testing team, release, and support).",
      "Produce fully functional mobile applications writing clean code and following SDLC.",
      "Troubleshoot and debug to optimize performance.",
      "Design interfaces to improve the user experience.",
      "Ensure applications meet quality standards.",
      "Working with the test team and UI tests to identify malfunctions.",
      "Should be flexible to design and build the apps on Xamarin Platforms.",
    ],
    qualifications: [
      "2 to 4 years of experience",
      "Experience in mobile application development on iOS and/or Android and/or Xamarin platform.",
      "Hands on experience in cross-platform mobile application development technologies.",
      "Experience in consuming and understanding of web services (REST).",
      "Solid exposure to object-oriented design patterns and multi-threading.",
      "Knowledge of Android application basics - Activities, Services, intents",
      "Excellent analytical skills with a good problem-solving attitude.",
    ],
    skills: [
      "Knowledge of SQL, ASP.NET, Web API, MVC will have added advantage.",
      "Familiarity with cloud message APIs and push notifications.",
      "Familiarity with offline storage and performance tuning.",
      "Knowledge in version control/code repository tools like Bitbucket, Github etc.",
      "Knowledge of Agile development processes and techniques.",
    ],
  },
  {
    slug: "Database_Admin",
    title: "Database Admin",
    experience: "4 to 6 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Manage SQL Server databases through multiple product lifecycle environments, from development to mission-critical production systems.",
      "Hands on experience on Log Shipping, Mirroring, Replication.",
      "Configure and maintain database servers and processes, including monitoring of system health and performance, to ensure high levels of performance, availability, and security.",
      "Apply data modeling techniques to ensure development and implementation support efforts meet integration and performance expectations.",
      "Independently analyze, solve, and correct issues in real time, providing problem resolution end-to-end.",
      "Refine and automate regular processes, track issues, and document changes.",
      "Assist developers with complex query tuning and schema refinement.",
      "Experience with backups, restores and recovery model.",
      "Perform scheduled maintenance and support release deployment activities after hours.",
      "Share domain and technical expertise, providing technical mentorship and cross-training to other peers and team members.",
    ],
    qualifications: [
      "4+ years MS SQL Server Administration experience required.",
      "Experience with Performance Tuning and Optimization (PTO), using native monitoring and troubleshooting tools.",
      "Experience with backups, restores and recovery models.",
      "Knowledge of High Availability (HA) and Disaster Recovery (DR) options for SQL Server.",
      "Experience working with Windows server, including Active Directory.",
      "Excellent written and verbal communication.",
      "Flexible, team player, “get-it-done” personality.",
      "Ability to organize and plan work independently.",
      "Ability to work in a rapidly changing environment.",
      "Ability to multi-task and context-switch effectively between different activities and teams.",
      "MCTS, MCITP, and/or MVP certifications a plus.",
    ],
  },
  {
    slug: "Project_Coordinator",
    title: "Project Coordinator",
    experience: "3 to 5 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Attend meetings and assist with determination of project documentation requirements.",
      "Provide project administration support, direct and monitor the requirements.",
      "Track the progress and quality of work being performed by team.",
      "Create and maintain MOM of the meetings.",
      "Use project scheduling and control tools to monitor projects plans and work hours.",
      "Effectively and accurately communicate relevant project information to the client and project team.",
      "Ensure client needs are met in a time and maintain Contract Execution Tracking Log.",
      "Identify and escalate priority issues.",
      "Cooperate in determining benchmark figures for project implementation and decision documents for project release.",
      "Plan project progress (define sub goals, milestones and tasks, time and resource planning).",
      "Plan personnel utilization (determine responsibilities, personnel planning).",
      "Manage project personnel responsible for implementation of the project tasks (hold and chair regular works meetings, motivate staff, manage conflicts and crises).",
      "Monitor project progress and success (assess risks and hazards to the success of the project and take appropriate measures for avoidance).",
      "Document project progress (project file, project log).",
      "Analyze user specifications and requirements and convert into Wireframes, Able to estimate the deliverable and deliver it on time.",
      "Document the problems and resolutions for future reference.",
      "Mentor and ensure team continually strive for improvement and efficiency gains.",
      "Understand the functionality of application and keep the team updated.",
      "Track and follow up on the pending approvals from Client related to UX.",
      "Maintain consistency in the icons, fonts, styles, functionalities.",
    ],
    qualifications: ["3 to 5 Years Experience"],
  },
  {
    slug: "Technical_Writer",
    title: "Technical Writer",
    experience: "3 - 5 YRS OF EXPERIENCE",
    jobcode: "PI023",
    responsibilities: [
      "Work with internal teams to obtain in depth understanding of the product and the documentation requirements.",
      "Produce high quality documentation that meets applicable standards and is appropriate for its intended audience.",
      "Write easy-to-understand user interface text, online help and developer guides.",
      "Use photographs, drawings, diagrams, animation, and charts that increase users understanding.",
      "Analyze existing and potential content, focusing on reuse and single-sourcing opportunities.",
      "Create and maintain the information architecture.",
    ],
    qualifications: [
      "3 to 5 years of experience",
      "Experience in technical writing of software documentation.",
      "Ability to quickly grasp complex technical concepts and make them easily understandable in text and pictures.",
      "Excellent written skills in English.",
      "Strong working knowledge of Microsoft Office.",
      "Familiarity with the Software Development Life Cycle.",
    ],
  },
  // ... add other jobs here (same structure as your JSON)
];
