export const teammember = [
  {
    id: 1,
    name: "Shyamal Swali",
    image: "/assets/img/about-us/team-images/shyamal.jpg",
    designation: "Founder & Director",
    linkedin: "https://in.linkedin.com/in/shyamal-swali-b6a23169",
  },
  {
    id: 2,
    name: "Hiten Damania",
    image: "/assets/img/about-us/team-images/hiten.jpg",
    designation: "Head of Delivery",
    linkedin: "https://in.linkedin.com/in/hiten-damania",
  },
  {
    id: 3,
    name: "Tarun Kapadia",
    image: "/assets/img/about-us/team-images/tarun.jpg",
    designation: "Product Delivery Lead",
    linkedin: "https://in.linkedin.com/in/tarun-kapadia-89965645",
  },
  {
    id: 4,
    name: "Hemang Choksi",
    image: "/assets/img/about-us/team-images/hemang.jpg",
    designation: "Lead Solution Architect",
    linkedin: "https://in.linkedin.com/in/hemang-choksi",
  },
  {
    id: 5,
    name: "Sagar Shirke",
    image: "/assets/img/about-us/team-images/sagar.jpg",
    designation: "Product Implementation Lead",
    linkedin: "https://in.linkedin.com/in/sagar-shirke-2581bb23",
  },
  {
    id: 6,
    name: "Firdaus Minocher",
    image: "/assets/img/about-us/team-images/firdaus.jpg",
    designation: "Business Process Strategist",
    linkedin: "https://in.linkedin.com/in/firdaus-minocher-4a136173",
  },
  {
    id: 7,
    name: "Abhijit Wagh",
    image: "/assets/img/about-us/team-images/abhijit.jpg",
    designation: "Product Implementation Lead",
    linkedin: "https://in.linkedin.com/in/abhi-wagh",
  },
  {
    id: 8,
    name: "Punit Jain",
    image: "/assets/img/about-us/team-images/punit.jpg",
    designation: "Product Manager",
    linkedin: "https://in.linkedin.com/in/punitjain1989",
  },
];

export const executiveteam = [
  {
    id: 1,
    name: "Vibhavari Gorakh",
    image: "/assets/img/about-us/team-images/vibhavari.jpg",
    designation: "Technical Lead - Data Platforms",
    linkedin: "https://in.linkedin.com/in/vibhavari-gorakh-25b8421a4",
  },
  {
    id: 2,
    name: "Khyati Parikh",
    image: "/assets/img/about-us/team-images/khyati.jpg",
    designation: "Product Manager",
    linkedin: "https://in.linkedin.com/in/khyati-parikh-6b6b55a4",
  },
  {
    id: 3,
    name: "Pravin Jadhav",
    image: "/assets/img/about-us/team-images/pravin.jpg",
    designation: "Web Development Lead",
    linkedin: "https://in.linkedin.com/in/pravinjd87",
  },
  {
    id: 4,
    name: "Monaz Katila",
    image: "/assets/img/about-us/team-images/monaz.jpg",
    designation: "Design Lead",
    linkedin: "https://in.linkedin.com/in/monaz-katila-94537684",
  },
  {
    id: 5,
    name: "Shivam Vyas",
    image: "/assets/img/about-us/team-images/shivam.jpg",
    designation: "Application Support Lead",
    linkedin: "https://in.linkedin.com/in/shivamnvyas",
  },
  {
    id: 6,
    name: "Payal Selvaswala",
    image: "/assets/img/about-us/team-images/payal.jpg",
    designation: "H.R.",
    linkedin: "https://in.linkedin.com/in/payal-selvaswala-8094b1215",
  },
  {
    id: 7,
    name: "Rajendra & Vicky",
    image: "/assets/img/about-us/team-images/infra-service-lead.jpg",
    mobImage: "/assets/img/about-us/team-images/infra-service-lead-mob.jpg",
    designation: "Infrastructure Services Lead",
    gridsize: 6,
  },
  {
    id: 8,
    name: "Rakesh, Manoj & Dakshata",
    image: "/assets/img/about-us/team-images/administrative-team.jpg",
    mobImage: "/assets/img/about-us/team-images/administrative-team-mob.jpg",
    designation: "Admin Squad",
    gridsize: 6,
  },
  {
    id: 9,
    name: "Nitin, Anil & Ashok bhau",
    image: "/assets/img/about-us/team-images/support_team.jpg",
    mobImage: "/assets/img/about-us/team-images/support_team_mob.jpg",
    designation: "GroundOps Crew",
    gridsize: 12,
  },
];
